### ISSUE TITLE
question about filter threshold

### ISSUE THREAD

**Issue by kevinlee9** [ascust/BDWSS#1]
Hi @ascust, when I looked up  filter thresholds of web images in config.py, I found below configs
```
FG_TH_CURCLASS_LOW = 0.1 # the current class pixels at least take 30% of the whole image
FG_TH_CURCLASS_HI = 0.8 # the current class pixels should not exceed 70% of the whole image
FG_TH_OTHER_HI = 0.3 # other class pixels cannot exceed 10%
```
However, In the paper they are 0.3, 0.7 and 0.1, which one should I use? thanks

**Comment by ascust** [comment]
Hi @kevinlee9 Sorry for the inconsistency. I think it could be that the version in the paper was way before this released version, and I forgot to change it back. But as far as I can remember, these parameters are not that sensitive. It is like 0.1, 0.8, 0.3 are more loose ones. My recommendation is you can start with the default settings in this version. you can play with the parameters later on if necessary. Sorry for the confusion.

**Comment by kevinlee9** [comment]
@ascust Thanks, and are web images provided in the github link all filtered? I notice its number is exactly 76.7k

**Comment by ascust** [comment]
Yes, that is like a subset. The original dataset is too large to upload. If you like you can create your own web dataset using web crawlers, as long as you follow the naming convention. All my images are from "Bing".
