### ISSUE TITLE
The pretrained model

### ISSUE THREAD

**Issue by DQDH** [ascust/BDWSS#3]
Hi, @ascust ,I can't open the link for pretrained model, can you show me a new link?

**Comment by ascust** [comment]
Do you have access to OneDrive? Since it is a OneDrive link, could you make sure you have access to OneDrive?

**Comment by DQDH** [comment]
@ascust . I'm very sorry to say that i can't access to OneDrive, can you show me another link? Thanks a lot.

**Comment by ascust** [comment]
@hardBird123 Could you try using a VPN to get access at the moment? It is quite troublesome to port it to somewhere else.

**Comment by DQDH** [comment]
@ascust Okay.I will have a try. The model vgg_20M in this link http://liangchiehchen.com/projects/Init%20Models.html  is the pretrained model you used?

**Comment by ascust** [comment]
Since my method uses SEC as the starting point, so the model is from
https://github.com/kolesman/SEC
It is a Caffe model. I converted it into MXNet format.
